const express = require('express')
const app = express();
const router=express.Router();
const  jwt = require('jsonwebtoken');
const bcrypt = require('bcrypt');
const crypto= require('crypto')
const cookieParser = require('cookie-parser')
const mongoose = require("mongoose")
const path = require('path');
const cors = require('cors');
const multer = require('multer');
const UserModel = require('../models/UserModel');
const FlightModel = require('../models/FlightModel');
const BookingModel = require('../models/BookingModel');
const ContactModel = require('../models/ContactModel');